# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 07:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LDA', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='connection',
            old_name='building',
            new_name='Building',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='connected',
            new_name='Connected',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='distance',
            new_name='Distance',
        ),
        migrations.RenameField(
            model_name='connection',
            old_name='transformer',
            new_name='Transformer',
        ),
    ]
