# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-21 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LDA', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Load', models.FloatField()),
                ('Time', models.DateTimeField()),
                ('Transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LDA.Transformer')),
            ],
        ),
    ]
